class Rules {

  Rules(){
    print("Rules instancié");
  }


  List<String> gif = [
    "well_done.gif",
    "truth_or_Dare.gif",
    "3_drink_laidies.gif",
    "lucky_case.gif",
    "5_Glasse.gif",
    "challenge.gif",
    "7_guys_drink.gif",
    "truth_or_Dare.gif",
    "9_beard.gif",
    "10_purple.gif",
    "11_sport.gif",
    "12_years_odd.gif",
    "challenge.gif",
    "14_in_advance.gif",
    "new_rule.gif",
    "16_piercing.gif",
    "lucky_case.gif",
    "18_shifumi.gif",
    "challenge.gif",
    "20_even_years.gif",
    "21_too_slow.gif",
    "22_trap.gif",
    "lucky_case.gif",
    "truth_or_Dare.gif",
    "25_long_hair.gif",
    "challenge.gif",
    "27_family.gif",
    "28_cupid.gif",
    "29_ly.gif",
    "new_rule.gif",
    "31_tatoo.gif",
    "32_wc.gif",
    "lucky_case.gif",
    "34_scottish.gif",
    "35_virgin.gif",
    "challenge.gif",
    "37_rich.gif",
    "38_stranger.gif",
    "truth_or_Dare.gif",
    "40_right.gif",
    "lucky_case.gif",
    "42_love.gif",
    "43_poor.gif",
    "challenge.gif",
    "new_rule.gif",
    "46_consonant.gif",
    "47_smoke.gif",
    "48_text.gif",
    "49_shutup.gif",
    "50_slave.gif",
    "lucky_case.gif",
    "52_sing.gif",
    "challenge.gif",
    "54_phone.gif",
    "55_joke.gif",
    "56_immunity.gif",
    "lucky_case.gif",
    "58_voyelle.gif",
    "challenge.gif",
    "truth_or_Dare.gif",
    "61_test.gif",
    "62_left.gif",
    "63_victory.gif"
  ];

  List<String> title = [
    "1. Ca commence bien...",
    "2. Action ou Vérité",
    "3. Santé mes Demoiselles",
    "4. Case chance",
    "5. Les bigleux",
    "6. Mini-jeux",
    "7. Santé les gars",
    "8. Action ou Vérité",
    "9. Les poilus",
    "10. Purple",
    "11. Les sportifs",
    "12. Année impaire",
    "13. Mini-jeux",
    "14. En avance",
    "15. Nouvelle règle",
    "16. Percé",
    "17. Case chance",
    "18. Pierre-papier-ciseaux",
    "19. Mini-jeux",
    "20. Année paire",
    "21. En retard",
    "22. Piège",
    "23. Case chance",
    "24. Action ou Vérité",
    "25. Cheveux longs",
    "26. Mini-jeux",
    "27. La mif",
    "28. Les destin liés",
    "29. Les siroteurs",
    "30. Nouvelle règle",
    "31. Tatouage",
    "32. Petite vessie",
    "33. Case chance",
    "34. Les écossais",
    "35. Les puceaux",
    "36. Mini jeux ",
    "37. Riche",
    "38. L'étranger",
    "39. Action ou Vérité",
    "40. A ta droite",
    "41. Case chance",
    "42. Les amoureux",
    "43. Les pauvres",
    "44. Mini jeux",
    "45. Nouvelle règle",
    "46. Consonne",
    "47. Fumeur",
    "48. SMS mortel",
    "49. Muet",
    "50. Esclave",
    "51. Case chance",
    "52. Une chanson",
    "53. Mini jeux",
    "54. Téléphone",
    "55. Une blague",
    "56. Collier d'immunité",
    "57. Case chance",
    "58. Voyelles",
    "59. Mini-jeux",
    "60. Action ou Vérité",
    "61. Test d'alcoolémie",
    "62. A ta gauche",
    "63. Victoire"
  ];

  List<String> rule = [
    "Seulement 1 pour ton premier lancé, bravo champion!! Aller, tout le monde bois 1 gorgée pour s'échauffer.",
    "action ou vérité",
    "Toutes les filles boivent 1 gorgées.",
    "Case chance",
    "Tous ceux qui portent des lunettes ou des lentilles boivent 1 gorgée.",
    "Mini jeux",
    "Tous les garçons boivent 2 gorgées.",
    "action ou vérité",
    "Tous ceux qui portent une barbe (même pas ouf) ou une moustache boivent 2 gorgées.",
    "Compte jusqu'à trois et annonce une couleur. Le dernier des joueurs qui touche un objet de cette couleur bois 2 gorgées.",
    "Tous ceux qui vont à la salle ou font du sport régulièrement boivent 2 gorgées.",
    "Tous ceux qui sont nés une année impaire boivent 1 gorgée.",
    "Mini jeux",
    "Tous les joueurs et joueuses qui ont leurs pions en retard par rapport à toi dans le jeux boivent 2 gorgées. Si tes dernier tant pis pour toi, bois autant de gorgées qu'il y a de joueur.",
    "Définit une nouvelle règle et combien de gorgée combien de gorgée pour ceux qui ne la respecterons pas. La règle s'applique tant qu'un autre joueur ne tombe pas de nouveau sur une cas 'Nouvelle règle'.",
    "Tous ceux qui portent des boucles d'oreilles ou percings boivent 1 gorgée.",
    "Case chance",
    "Joue une manche de Pierre-papier-ciseaux avec chacun des joueurs, distribut autant de gorgée que tu auras gagné de manche.",
    "Mini jeux",
    "Tous ceux qui sont nés une année paire boivent 2 gorgées.",
    "Bois autant de gorgées qu'il y a de joueurs devant toi dans le jeux.",
    "Pas de chance... Bois deux gorgées, c'est cadeau.",
    "Case chance",
    "action ou vérité",
    "Boivent 1 gorgée toutes celles et ceux ont les cheveux longs.",
    "Mini jeux",
    "Boivent 2 gorgées tout ceux qui jouent en couple ou avec un ou plusieurs menbres de leur famille.",
    "Choisis quelqu'un parmis les autres, vous êtes maintenant liés! Tous ce que l'un boit, l'autre aussi.",
    "Celui qui a son verre le plus remplie et ne fais que siroter depuis le début boit cul-sec. On t'as tous vu!",
    "Définit une nouvelle règle et combien de gorgée combien de gorgée pour ceux qui ne la respecterons pas. La règle s'applique tant qu'un autre joueur ne tombe pas de nouveau sur une cas 'Nouvelle règle'.",
    "Ceux et celles qui portent au moins un tatouage boivent 1 gorgée.",
    "Le prochain joueur ou joueuse qui va aux WC devra boire cul-sec.",
    "Case chance",
    "Boivent 1 gorgée toutes celles et ceux qui portent une jupes ou une chemise à carreaux.",
    "Ceux qui n'ont jamais fait l'amour boivent 2 gorgées.",
    "Mini jeux",
    "Donne 2 gorgées si tu as plus de 15€ sur toi.",
    "Les autres joueurs décident d'un accent que tu devras emprunter à chaque fois que tu parles pendants 3 tours. 1 gorgée à chaque fois que tu oublies.",
    "action ou vérité",
    "Bois 2 gorgées dans le verre de ton voisin de droite.",
    "Case chance",
    "Boivent 1 gorgée tous ceux qui sont en couple. ",
    "Bois une gorgée si tu as moins de 10€ sur toi.",
    "Mini jeux",
    "Définit une nouvelle règle et combien de gorgée combien de gorgée pour ceux qui ne la respecterons pas. La règle s'applique tant qu'un autre joueur ne tombe pas de nouveau sur une cas 'Nouvelle règle'.",
    "Bois autant de gorgées qu'il y a de consonne dans ton prénom.",
    "Tous ceux qui fument à l'instant boivent 2 gorgées.",
    "Les autres joueurs ont le droit de prendre ton téléphone pour envoyer le SMS qu'ils veulent à la personne de leur choix. Ce SMS devra par contre contenir qu'un seul mot. Bois cul-sec si tu refuse.",
    "Si tu parles jusqu'à ton prochain tour, bois 5 gorgées.",
    "Choisis un joueur ou une joueuse, il ou elle sera ton escalve pendant 2 tours.",
    "Case chance",
    "Tous les autres joueurs choisissent une chanson, chante AU MOINS le refrain ou bois cul-sec.",
    "Mini jeux",
    "Tout ceux et celles qui sont actuellement sur leurs téléphones boivent 2 gorgées.",
    "Raconte une blague à tout le monde. Si personne ne rigole bois juste une gorgée et si tu n'en trouves pas bois en 5.",
    "Tout le monde bois une gorgée sauf toi.",
    "Case chance",
    "Bois autant de gorgées qu'il y a de voyelle dans ton prénom.",
    "Mini jeux",
    "action ou vérité",
    'Récite le plus vite possible : "Un chasseur sachant chasser sans son chien est un bon chasseur." Distribut 2 gorgées si tu réussis, sinon bois les.',
    "Bois 2 gorgées dans le verre de ton voisin de gauche.",
    "Félicitation"
  ];

}